trigger: none

pool:
  vmImage: windows-latest

variables:
  buildOutput: '$(Build.ArtifactStagingDirectory)/publish'
  testResults: '$(Build.ArtifactStagingDirectory)/TestResults'

steps:
- checkout: self
  clean: true

# Step 1: Install .NET 8 SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

# Step 2: Restore dependencies
- script: |
    echo Restoring dependencies...
    dotnet restore
  displayName: 'Restore Dependencies'

# Step 3: Build the project
- script: |
    echo Building the project...
    dotnet build --configuration Release --no-restore
  displayName: 'Build Solution'

# Step 4: Run Unit Tests using VSTest and Collect Code Coverage
- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\Release\**\*.Test.dll
      **\bin\Release\**\*Tests.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    platform: 'x64'
    configuration: 'Release'
    otherConsoleOptions: '/Logger:trx /Collect:"Code Coverage"'
    resultsFolder: '$(testResults)'
  displayName: 'Run Unit Tests and Collect Code Coverage'
  continueOnError: true

# Step 5: Debugging Step (Optional - Check TestResults Directory)
- script: |
    echo "Checking test results directory..."
    dir "$(testResults)" /s
  displayName: 'Debug: List TestResults Directory'

# Step 6: Publish Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/*.trx'
    searchFolder: '$(testResults)'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'Unit Test Results - $(Build.BuildId)'
  condition: succeededOrFailed()
  displayName: 'Publish Test Results'

# Step 7: Publish Code Coverage Results
- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(testResults)/**/coverage.cobertura.xml'
    reportDirectory: '$(testResults)/CoverageReport'
    failIfCoverageEmpty: false  # Avoid pipeline failure if no coverage report is found
  condition: succeededOrFailed()
  displayName: 'Publish Code Coverage Report'

